"""Create users table

Revision ID: 0001_initial_users
Revises:
Create Date: <timestamp>

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # For Enum

# revision identifiers, used by Alembic.
revision = "0001_initial_users" # Example revision ID
down_revision = None
branch_labels = None
depends_on = None

# Import UserRole from your models to use in migration
# This path might need adjustment based on how Alembic runs
# Assuming alembic is run from 'backend' directory, or PYTHONPATH is set up
from models.user import UserRole

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("email", sa.String(), nullable=False),
    sa.Column("hashed_password", sa.String(), nullable=False),
    sa.Column("full_name", sa.String(), nullable=True),
    sa.Column("is_active", sa.Boolean(), nullable=True, server_default=sa.text("true")),
    sa.Column("is_verified", sa.Boolean(), nullable=True, server_default=sa.text("false")),
    sa.Column("role", postgresql.ENUM(UserRole, name="userrole", create_type=True), nullable=False, server_default=UserRole.CONSULTANT.value),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_full_name"), "users", ["full_name"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_full_name"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # Potentially drop the ENUM type if it was created by this migration explicitly
    op.execute("DROP TYPE IF EXISTS userrole;")
    # ### end Alembic commands ###
